---
title: "sub_condition_one|stat_comp_report"
author: "ZJH"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# init
```{r,init}
library(MyToolBox)
library(assertthat)
library(invgamma)
library(LearnBayes)
data("birthweight")
library(lattice)
mygender <- with(birthweight, ifelse(birthweight$gender==0,"Male","Female"))
dotplot(mygender ~ weight, data = birthweight,
xlab = "Birthweight", ylab = "Gender")
```

# distributions
```{r}
dinvgamma <- function(x,shape,scale){
  fx <- (scale^shape*exp(-scale/x)*x^(-shape-1))/gamma(shape)
  return(fx)}
Cauchy_plus <- function(x,b_cauchy){
  assert_that(b_cauchy>0)
  fx <- 2/pi/(b_cauchy*(1+(x/b_cauchy)^2)*(x>0))
  return(fx)
}
prob <- function(x,shape,scale,b_cauchy){
  fx <- dinvgamma(x^2,shape =shape,scale=scale)*Cauchy_plus(x,b_cauchy=b_cauchy)
  return(fx)
}
```

# functions
A-R method
```{r}
accept_reject_K_invG <- function(a,b,K,fx,...)
{
  while(TRUE)
  {
    x <- rinvgamma(1,a,b)
    y <- runif(1,0,K) # choose a # from 0 to k 
    if(y<fx(x,...)/dinvgamma(x,shape=a,scale=b)) # compare f(x) and y until y<fx(x),only reserve the y in the domain we want.
      break
  }
  return(x)
}
```

data multiply
```{r}

collected_data_from <- function(data_producer,times,...)
{
  Observations <- rep(0,times) 
  for (i in 1:times) 
  {
    Observations[i] <- data_producer(...)
  }
  return(Observations)
}
```

```{r}
draw <- function(fx,Observation,...)
{
  hist(Observation,nclass=25,freq = FALSE,main="")
  curve(fx(x,...),add=TRUE,lty = 2, lwd = 2,col='red')
}
```

# gogogo
# parameters
```{r}
b_tau <- 1# i don't know what actually is,for cauchy plus(0,b_tau)
a <- 1 # for proposal distribution inverse gamma(a,b) 
b <- 1 # for proposal distribution inverse gamma(a,b)
```

```{r}
Cmax <- Cauchy_plus(10^-8,b_tau)
dat <- collected_data_from(accept_reject_K_invG,times=1000,a = a,b = b,K = Cmax,fx=Cauchy_plus,b_cauchy=b_tau)
draw(Cauchy_plus,dat %>%sort() %>%  head(950),b_cauchy=b_tau)
```
```{r}

```

