---
title: "sub_condition_three|stat_comp_report"
author: "ZJH"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# init
```{r,init}
library(assertthat)
library(invgamma)
library(LearnBayes)
data("birthweight")
library(lattice)
library(boa)
library(coda)
```

# distributions
```{r}
dinvgamma <- function(x,shape,scale){
  assert_that(x!=0)
  assert_that(shape!=0)
  fx <- (scale^shape*exp(-scale/x)*x^(-shape-1))/gamma(shape)
  return(fx)}
Cauchy_plus <- function(x,b_cauchy){
  assert_that(b_cauchy>0)
  fx <- 2/pi/(b_cauchy*(1+(x/b_cauchy)^2)*(x>0))
  return(fx)
}
prob <- function(x,shape,scale,b_cauchy){
  fx <- dinvgamma(x^2,shape =shape,scale=scale)*Cauchy_plus(x,b_cauchy=b_cauchy)
  assert_that(dinvgamma(x^2,shape =shape,scale=scale)!=0)
  assert_that(Cauchy_plus(x,b_cauchy=b_cauchy)!=0)
  assert_that(fx!=0)
  return(fx)
}

```

# functions

# gogogo
# parameters for model
```{r}
b_tau <- 1# i don't know what actually is,for cauchy plus(0,b_tau)
a <- 1 # for proposal distribution inverse gamma(a,b) 
b <- 1 # for proposal distribution inverse gamma(a,b)
```
# parameters for simulation process
```{r}
m <- 500 #length of chain
xt <- numeric(m)
# generate the observed sample
xt[1] <- rchisq(1,df =100)
counter <- 0
# generate the independence sampler chain
u <- runif(m)
for (i in 2:m) {
  y <- rchisq(1,df = xt[i-1]) #proposal distribution
  fy <- prob(x = y,shape = a,scale =b,b_cauchy = b_tau)
  fx <- prob(x = xt[i-1],shape = a,scale =b,b_cauchy = b_tau)
  assert_that(fx!=0)
  r <- prod(fy / fx) *
    dchisq(xt[i-1],df=y) /
    dchisq(y,df=xt[i-1])
  if (u[i] <= r){
    xt[i] <- y 
  }else 
  {
    xt[i] <- xt[i-1]
  }
}
```

```{r}
draw(prob,xt[51:m] %>% sort() %>% head(8500,),shape = a,scale = b,b_cauchy = b_tau)
```
```{r}
patient3 <- mcmc(xt)
traceplot(patient3)
densplot(patient3)
meanplot <- function(patient)
{
mean <- patient%>% cumsum()
mean <- mean/1:length(patient)
plot(mean)
}
meanplot(patient3)
heidel.diag(patient3)
raftery.diag(patient3)
autocorr.plot(patient3)
```
